server:
  port: 8080  # Spring boot Server port

spring:
  h2:
    console:
      enabled: true  # H2 웹 콘솔을 사용하겠다는 의미
      path: /h2-console  # 콘솔의 경로

  datasource:
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: jdbc:h2:file:~/kyu/db_test;AUTO_SERVER=TRUE  #접속 URL
    username: test  # 사용자 이름 (로그인 시 사용)
    password: 1234   # 사용자 암호 (로그인 시 사용)

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
